blank_issues_enabled: false
contact_links:
  - name: Unsure what is happening? or want to know more about Private Retrieval Fund
    url: https://github.com/DeepLab/arcological/issues
    about: Read more about Private Retrieval Fund here
